context("Adding and plotting the weight function")
test_that("Plotting the weight function works", {
  expect_silent(plotWf(yangObj, "nn"))
  expect_is(plotWf(yangObj, "nnPair"), "ggplot")
  expect_silent(plotWf(objBG, "nn"))
  expect_silent(plotWf(objBG, "allDist"))
  expect_silent(plotWf(objBG, "nnCell"))
  expect_silent(plotWf(objBG, "allDistCell"))
  expect_is(plotWf(objBG, "nnPair"), "ggplot")
  expect_is(plotWf(objBG, "allDistPair"), "ggplot")
  expect_is(plotWf(objBG, "nnPairCell"), "ggplot")
  expect_is(plotWf(objBG, "allDistPairCell"), "ggplot")
})
test_that("Plotting the weight function application throws errors where appropriate", {
  expect_error(plotWf(piEstsBG))
})
