context("Test building of dataframes of probabilistic indices for mixed model building")
test_that("Building data frames for mixed modelling proceeds without errors", {
    expect_message(dfBG0 <- buildDfMM(piEstsBG, gene = "gene1", hypFrame = hypFrame2, pi = "nn"))
    #No weight fuction
    expect_s3_class(dfBG1 <- buildDfMM(piEstsBG, gene = "gene1", hypFrame = hypFrame2, pi = "nn", weightFunction = wf), "data.frame")
    expect_s3_class(dfBG2 <- buildDfMM(piEstsBG, gene = "gene1--gene2", hypFrame = hypFrame2, pi = "nnPair", weightFunction = wfPair), "data.frame")
    expect_s3_class(dfBG2b <- buildDfMM(piEstsBG, gene = c("gene1", "gene2"), hypFrame = hypFrame2, pi = "nnPair", weightFunction = wfPair), "data.frame")
    expect_identical(dfBG2, dfBG2b)
    expect_s3_class(dfBG3 <- buildDfMM(piEstsBG, hypFrame = hypFrame2, gene = "gene1", pi = "allDist", weightFunction = wfAll), "data.frame")
    expect_s3_class(dfBG4 <- buildDfMM(piEstsBG, hypFrame = hypFrame2, gene = "gene1--gene2", pi = "allDistPair"), "data.frame")
    expect_silent(dfBG5 <- buildDfMM(piEstsBG, hypFrame = hypFrame2, gene = "gene1", pi = "midpoint"))
    expect_silent(dfBG6 <- buildDfMM(piEstsBG, hypFrame = hypFrame2, gene = "gene10", pi = "fixedpoint"))
    expect_silent(dfBG7 <- buildDfMM(piEstsBG, hypFrame = hypFrame2, gene = "gene1", pi = "edge"))
    expect_silent(dfCSR1 <- buildDfMM(piEstsCSR, hypFrame = hypFrame2, gene = "gene23", pi = "edge"))
    expect_silent(dfCSR2 <- buildDfMM(piEstsCSR, hypFrame = hypFrame2, gene = "gene2", pi = "fixedpoint"))
    expect_silent(dfCSR3 <- buildDfMM(piEstsCSR, hypFrame = hypFrame2, gene = "gene2", pi = "midpoint"))
    expect_s3_class(dfCSR4 <- buildDfMM(piEstsCSR, hypFrame = hypFrame2, gene = "gene2", pi = "allDist", weightFunction = wfCSRall), "data.frame")
    expect_s3_class(dfCSR5 <- buildDfMM(piEstsCSR, hypFrame = hypFrame2, gene = "gene20", pi = "nn", weightFunction = wfCSR), "data.frame")
    expect_s3_class(dfCSR6 <- buildDfMM(piEstsCSR, hypFrame = hypFrame2, gene = "gene2--gene20", pi = "nnPair", weightFunction = wfCSRPair), "data.frame")
    expect_s3_class(dfCSR7 <- buildDfMM(piEstsCSR, hypFrame = hypFrame2, gene = "gene2--gene23", pi = "allDistPair", weightFunction = wfCSRAllPair), "data.frame")
    expect_true(all(is.na(dfCSR7$pi) | (dfCSR7$pi > 0 & dfCSR7$pi < 1)))
    expect_true(all(is.na(dfBG3$pi) | (dfBG3$pi > 0 & dfBG3$pi < 1)))
})
piEstsCSR2 <- estPims(hypFrame2, pis = c("nn"), features = c("gene1", "gene2"),
                     point = c(0.5, 0.5), null = "CSR")
test_that("Building data frames throws errors where appropriate", {
    expect_error(buildDfMM(piEstsCSR, hypFrame = hypFrame2, gene = c("gene1", "gene2"), pi = "nn"))
    expect_error(buildDfMM(piEstsCSR, hypFrame = hypFrame2, gene = "gene1", pi = "Kest"))
    expect_error(buildDfMM(piEstsBG, hypFrame = hypFrame2, gene = "protein1", pi = "nn"))
    expect_error(buildDfMM(piEstsCSR2, hypFrame = hypFrame2, gene = "gene1", pi = "allDist"))
    expect_error(buildDfMM(piEstsCSR2, hypFrame = hypFrame2, gene = "gene1--gene2", pi = "nnPair"))
    expect_error(buildDfMM(piEstsBG, gene = c("gene1", "gene2"), hypFrame = hypFrame2, pi = "nn"))
    expect_error(buildDfMM(piEstsBG, gene = "gene1_gene2", hypFrame = hypFrame2, pi = "nn"))
    expect_error(buildDfMM(piEstsBG, gene = "gene1", hypFrame = hypFrame2, pi = "nnPair"))
    expect_error(buildDfMM(piEstsBG, gene = c("gene1", "gene2", "gene3"), pi = "nnPair", hypFrame = hypFrame2))
})
