context("Large scale mixed model fitting")
test_that("Fitting linear mixed models proceeds without errors", {
    expect_message(linModsNNint <- fitLMMs(yangObj, pi = "nn"))
    expect_message(linModsNNPairint <- fitLMMs(yangObj, pi = "nnPair"))
    expect_message(linModsNN <- fitLMMs(yangObj, fixedVars = "day", pi = "nn"))
    expect_message(linModsNNPair <- fitLMMs(yangObj, fixedVars = "day", pi = "nnPair"))
    expect_message(linMModsNN <- fitLMMs(yangObj, fixedVars = "day", randomVars = "root", pi = "nn"))
    expect_message(linMModsNNPair <- fitLMMs(yangObj, fixedVars = "day", randomVars = "root", pi = "nnPair"))
    #Returning the models
    expect_message(linModsNNfull <- fitLMMs(yangObj, fixedVars = "day", pi = "nn", returnModels = TRUE))
    expect_message(linMModsNNfull <- fitLMMs(yangObj, fixedVars = "day", randomVars = "root", pi = "nn", returnModels = TRUE))
    expect_s3_class(linModsNNfull$models[[1]], "lm")
    expect_s4_class(linMModsNNfull$models[[1]], "lmerModLmerTest")
    expect_message(fitLMMs(objBG, fixedVars = "condition", pi = "midpoint"))
    expect_message(fitLMMs(objBG, fixedVars = "condition", pi = "edge"))
})
test_that("Fitting linear mixed models throws errors where appropriate", {
    expect_error(fitLMMs(objBG, fixedVars = "condition", randomVars = "fov", pi = "midpoint"))
    expect_error(buildDfMM(objCSR, gene = "gene1", pi = "Kest"))
    expect_error(buildDfMM(objBG, gene = "protein1", pi = "nn"))
    expect_error(buildDfMM(objCSR2, gene = "gene1", pi = "allDist"))
    expect_error(buildDfMM(objCSR2, gene = "gene1--gene2", pi = "nnPair"))
    expect_error(buildDfMM(objBG, gene = c("gene1", "gene2"), i = "nn"))
    expect_error(buildDfMM(objBG, gene = "gene1_gene2", i = "nn"))
    expect_error(buildDfMM(objBG, gene = "gene1", i = "nnPair"))
    expect_error(buildDfMM(objBG, gene = c("gene1", "gene2", "gene3"), pi = "nnPair", hypFrame = hypFrame2))
})
