context("Large scale mixed model fitting")
test_that("Fitting linear mixed models proceeds without errors", {
    expect_message(linModsNNint <- fitLMMs(yangObj, pi = "nn"))
    expect_silent(linModsNNint <- fitLMMs(yangObj, pi = "nn", verbose = FALSE))
    expect_message(linModsNNPairint <- fitLMMs(yangObj, pi = "nnPair"))
    expect_message(linModsNN <- fitLMMs(yangObj, fixedVars = "day", pi = "nn"))
    expect_message(linModsNNPair <- fitLMMs(yangObj, fixedVars = "day", pi = "nnPair"))
    expect_message(linMModsNN <- fitLMMs(yangObj, fixedVars = "day", randomVars = "root", pi = "nn"))
    expect_message(linMModsNNPair <- fitLMMs(yangObj, fixedVars = "day", randomVars = "root", pi = "nnPair"))
    #Returning the models
    expect_message(linModsNNfull <- fitLMMs(yangObj, fixedVars = "day", pi = "nn", returnModels = TRUE))
    expect_message(linMModsNNfull <- fitLMMs(yangObj, fixedVars = "day", randomVars = "root", pi = "nn", returnModels = TRUE))
    expect_s3_class(linModsNNfull$models[[1]], "lm")
    expect_s4_class(linMModsNNfull$models[[1]], "lmerModLmerTest")
    expect_message(linModsMP <- fitLMMs(objBG, fixedVars = "condition", pi = "midpoint"))
    expect_message(linModsEdge <- fitLMMs(objBG, fixedVars = "condition", pi = "edge"))
    expect_is(resMat <- getResults(linModsMP, "Intercept"), "matrix")
    expect_is(resMatCond <- getResults(linModsEdge, "condition"), "matrix")
    expect_false(is.unsorted(getResults(linModsMP, "Intercept")[, "pVal"]))
})
test_that("Fitting linear mixed models throws errors where appropriate", {
    expect_error(fitLMMs(objBG, fixedVars = "condition", randomVars = "fov", pi = "midpoint"))
})
