context("Test building of dataframes of probabilistic indices for mixed model building")
test_that("Building data frames for mixed modelling proceeds without errors", {
    expect_silent(dfBG0 <- buildDfMM(objBG, gene = "gene1", pi = "nn"))
    expect_s3_class(dfBG1 <- buildDfMM(objBG, gene = "gene1", pi = "nn"), "data.frame")
    expect_s3_class(dfBG2 <- buildDfMM(objBG, gene = "gene1--gene2", pi = "nnPair"), "data.frame")
    expect_s3_class(dfBG2b <- buildDfMM(objBG, gene = c("gene1", "gene2"), pi = "nnPair"), "data.frame")
    expect_identical(dfBG2, dfBG2b)
    expect_s3_class(dfBG3 <- buildDfMM(objBG, gene = "gene1", pi = "allDist"), "data.frame")
    expect_s3_class(dfBG4 <- buildDfMM(objBG, gene = "gene1--gene2", pi = "allDistPair"), "data.frame")
    expect_silent(dfBG5 <- buildDfMM(objBG, gene = "gene1", pi = "midpoint"))
    expect_silent(dfBG6 <- buildDfMM(objBG, gene = "gene1", pi = "edge"))
    totPointsGene1 = sum(vapply(objBG$hypFrame$ppp, FUN.VALUE = double(1),
                        function(x) sum(marks(x, drop = TRUE)$gene == "gene1")))
    #For fixed points, number of PI must match number of events
    expect_equal(totPointsGene1, nrow(dfBG6))
    expect_equal(totPointsGene1, nrow(objBG$hypFrame))
    expect_s3_class(dfBG7 <- buildDfMM(objBG, gene = "gene1", pi = "nnCell"), "data.frame")
    expect_s3_class(dfBG8 <- buildDfMM(objBG, gene = "gene1", pi = "allDistCell"), "data.frame")
    expect_s3_class(dfBG9 <- buildDfMM(objBG, gene = "gene1--gene2", pi = "nnPairCell"), "data.frame")
    expect_s3_class(dfBG10 <- buildDfMM(objBG, gene = "gene1--gene2", pi = "allDistPairCell"), "data.frame")
    expect_silent(dfCSR1 <- buildDfMM(objCSR, gene = "gene23", pi = "edge"))
    expect_silent(dfCSR3 <- buildDfMM(objCSR, gene = "gene2", pi = "midpoint"))
    expect_s3_class(dfCSR4 <- buildDfMM(objCSR, gene = "gene2", pi = "allDist"), "data.frame")
    expect_s3_class(dfCSR5 <- buildDfMM(objCSR, gene = "gene20", pi = "nn"), "data.frame")
    expect_s3_class(dfCSR6 <- buildDfMM(objCSR, gene = "gene2--gene20", pi = "nnPair"), "data.frame")
    expect_s3_class(dfCSR7 <- buildDfMM(objCSR, gene = "gene2--gene23", pi = "allDistPair"), "data.frame")
    expect_s3_class(dfCSR8 <- buildDfMM(objCSR, gene = "gene1", pi = "nnCell"), "data.frame")
    expect_s3_class(dfCSR9 <- buildDfMM(objCSR, gene = "gene1", pi = "allDistCell"), "data.frame")
    expect_s3_class(dfCSR9 <- buildDfMM(objCSR, gene = "gene1--gene2", pi = "nnPairCell"), "data.frame")
    expect_s3_class(dfCSR11 <- buildDfMM(objCSR, gene = "gene1--gene2", pi = "allDistPairCell"), "data.frame")
    expect_true(all(is.na(dfCSR7$pi) | (dfCSR7$pi > 0 & dfCSR7$pi < 1)))
    expect_true(all(is.na(dfBG3$pi) | (dfBG3$pi > 0 & dfBG3$pi < 1)))
})
objCSR2 <- estPims(hypFrame2,
    pis = c("nn"), features = c("gene1", "gene2"),
    null = "CSR"
)
test_that("Building data frames throws errors where appropriate", {
    expect_error(buildDfMM(objCSR, gene = c("gene1", "gene2"), pi = "nn"))
    expect_error(buildDfMM(objCSR, gene = "gene1", pi = "Kest"))
    expect_error(buildDfMM(objBG, gene = "protein1", pi = "nn"))
    expect_error(buildDfMM(objCSR2, gene = "gene1", pi = "allDist"))
    expect_error(buildDfMM(objCSR2, gene = "gene1--gene2", pi = "nnPair"))
    expect_error(buildDfMM(objBG, gene = c("gene1", "gene2"), i = "nn"))
    expect_error(buildDfMM(objBG, gene = "gene1_gene2", i = "nn"))
    expect_error(buildDfMM(objBG, gene = "gene1", i = "nnPair"))
    expect_error(buildDfMM(objBG, gene = c("gene1", "gene2", "gene3"), pi = "nnPair", hypFrame = hypFrame2))
})
