# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossdistFastLocal <- function(m1, m2) {
    .Call(`_spatrans_crossdistFastLocal`, m1, m2)
}

crossdistFast <- function(m1, m2, pOutBigMat) {
    invisible(.Call(`_spatrans_crossdistFast`, m1, m2, pOutBigMat))
}

findRanksDist <- function(m1, m2, squaredDist) {
    .Call(`_spatrans_findRanksDist`, m1, m2, squaredDist)
}

rowSumsLarger <- function(m1, pInBigMat) {
    .Call(`_spatrans_rowSumsLarger`, m1, pInBigMat)
}

