# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossdistFastLocal <- function(m1, m2) {
    .Call(`_smoppix_crossdistFastLocal`, m1, m2)
}

findRanksDist <- function(coords, coordsLeft, NNDist) {
    .Call(`_smoppix_findRanksDist`, coords, coordsLeft, NNDist)
}

cpp_pnhyper <- function(x, n, m, r, lower_tail = TRUE, log_prob = FALSE) {
    .Call(`_smoppix_cpp_pnhyper`, x, n, m, r, lower_tail, log_prob)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_smoppix_RcppExport_registerCCallable`)
})
